### ISSUE TITLE
jnlp file of iDrop Desktop doesn't run on Mac OS

### ISSUE THREAD

**Issue by ganqqwerty** [INCF/ids-tools#20]
I identified the following problem with this file: http://iren-web.renci.org/idrop-release/idrop.jnlp on Mac OS X. After tuning the permissions and security this file is not running, displaying the following error: 

```
java.lang.SecurityException: Missing required Permissions manifest attribute in main jar: http://iren-web.renci.org/idrop-release/lib/idrop-swing-2.0.0.jar
    at com.sun.deploy.security.DeployManifestChecker.verifyMainJar(Unknown Source)
    at com.sun.deploy.security.DeployManifestChecker.verifyMainJar(Unknown Source)
    at com.sun.javaws.Launcher.doLaunchApp(Unknown Source)
    at com.sun.javaws.Launcher.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)


```

**Comment by brainstorm** [comment]
Please report this one upstream:

https://github.com/DICE-UNC/idrop

I think that @michael-conway will purchase proper code signing certificates for the app sooner or later to avoid this particular issue.

You can tune your security preferences to bypass this through the global OSX system settings panel.

**Comment by michael-conway** [comment]
Yes, we're looking at that and po's have been cut for the actual Install4J

MC

**Comment by ganqqwerty** [comment]
Roman, I propose to leave this ticket opened before we have the solution. Otherwise we will just forget about this problem

**Comment by michael-conway** [comment]
Roman,

We’ve abandoned JNLP altogether in favor of a plain Install4J platform installer. This runs on Mac.  JNLP and webstart have uniformly been a problem.

See:

https://code.renci.org/gf/download/frsrelease/217/2272/iDrop_macos_2_0_1.dmg

This is using the ‘demo’ of Install4J so it has a nag screen, and there is a purchase order in the works for  the full version.  Does that resolve this issue?

MC

**Comment by brainstorm** [comment]
Good point @michael-conway. @ganqqwerty, let us know if that fixes the problem for you.

I managed to get it to work tweaking the security settings, but I understand that regular users might have issues with that. As always your feedback and documentation is very appreciated, thanks for raising this issue.

**Comment by ganqqwerty** [comment]
Thanks @michael-conway , I'm trying DMG now

**Comment by michael-conway** [comment]
ok cool.  Let's close this and any issue you find we can have a separate ticket (to consider jnlp support depracated).

Note that we are waiting to get the full Install4J license, the check is in the mail, so to speak.

**Comment by ganqqwerty** [comment]
@michael-conway what file do I have to use for Linux and Windows platforms instead of jnlp?

**Comment by michael-conway** [comment]
Hi Yury look here:

https://github.com/DICE-UNC/idrop/wiki/iDrop-Installers

I will probably start a convention of '-latest' so that one may reliably
pick things up from clients that want to embed links.  When we get the
installer we can try and formalize a mechanism to point to the final
installer programs.  Maybe through the consortium.

**Comment by ganqqwerty** [comment]
Great! Thanks @michael-conway! That exactly what I needed! @brainstorm , can you please update the references to the installers here in the section "Desktop clients"?

**Comment by brainstorm** [comment]
Done!

**Comment by ganqqwerty** [comment]
oh, sorry, I did't attached th link to the word "here" :) 
it's section Desktop clients HERE: 
http://www.incf.org/resources/data-space/access-software-and-interfaces

**Comment by brainstorm** [comment]
Oh, cool, I will right now, I was fixing the Wiki pages over this repo, you can review the changes over here if you wish:

https://github.com/brainstorm?tab=activity

Thanks!
