### ISSUE TITLE
iDrop Web - bulk upload prints error

### ISSUE THREAD

**Issue by ganqqwerty** [INCF/ids-tools#21]
When I go to Bulk Upload I get ClassNotFound exception. Clicking at Details button doesn't show any details.

I use Oracle Java 7, Firefox browser, Ubuntu 14.04. The same is happening with Mac/Firefox.

![error](http://dl.dropbox.com/u/935446/Selection_019.png)!

**Comment by brainstorm** [comment]
Please report upstream, this has nothing to do with ids-tools:

https://github.com/DICE-UNC/idrop
