### ISSUE TITLE
Add rules referred in documentation and auditing .re's under incf.ids-tools/rules

### ISSUE THREAD

**Issue by brainstorm** [INCF/ids-tools#7]
As indicated in the documentation:

```
(...) Lastly, they will set up some iRODS rules that map your namespace 
to your data resource and an iRODS group (e.g. ids-dbio) that you can 
use for ACLs
```

These rules, including the audit ones, should be available in the package as well, for future reference, modifications, versioning, etc...

**Comment by cansmith** [comment]
See new wiki page for instructions on adding a data node:

https://github.com/INCF/ids-tools/wiki/IDS-Administrative-Tasks

**Comment by cansmith** [comment]
Many of the placeholder rules are in the ids-src.re.tmpl file in ids-tools/ids/fabfile/templates. More rules could be added here in terms of examples, but they should be commented out.

**Comment by cansmith** [comment]
I've removed ids-src.re from ids-tools/ids/rules as this is part of the installed ids python package, and instead moved the incf zone rules to ids-tools/docs/examples.
